const shows = [{
    "id": 1215,
    "title": "Young Sheldon",
    "translated_genres": "Comedy",
    "created_at": "2017-09-26T00:48:47.167+03:00",
    "length": 19,
    "year": "2017",
    "imdb_rating": 7.6,
    "desc": "The early life of child genius Sheldon, later n in \"The Big Bang Theory\" (2007).",
    "network": "CBS",
    "videos_count": 139,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1215/thumb_kidkbZRBGbsEIrX7pODRSKi9ipl.jpg",
    "url": "/en/shows/young-sheldon",
    "watched_count": null
}, {
    "id": 79,
    "title": "Grey's Anatomy",
    "translated_genres": "Drama, Romance",
    "created_at": "2012-10-14T01:38:08.865+04:00",
    "length": 43,
    "year": "2005",
    "imdb_rating": 7.6,
    "desc": "A drama centered on the personal and professional lives of five surgical interns and their supervisors.",
    "network": "American Broadcasting Company",
    "videos_count": 425,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/79/thumb_tnkYVbGDmpIcKWo7Synr4yqEsZM.jpg",
    "url": "/en/shows/greys-anatomy",
    "watched_count": null
}, {
    "id": 1511,
    "title": "The Rookie",
    "translated_genres": "Crime, Drama",
    "created_at": "2018-10-17T09:56:10.945+03:00",
    "length": 42,
    "year": "2018",
    "imdb_rating": 8.0,
    "desc": "Starting over isn’t easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force’s oldest rookie, he’s met with skepticism from some higher-ups who see him as just a walking midlife crisis.",
    "network": "ABC",
    "videos_count": 106,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1511/thumb_eh5fbHwK8GgBuib8vG8Ntok7ZAR.jpg",
    "url": "/en/shows/the-rookie",
    "watched_count": null
}, {
    "id": 1203,
    "title": "The Good Doctor",
    "translated_genres": "Drama",
    "created_at": "2017-09-12T21:49:23.885+03:00",
    "length": 42,
    "year": "2017",
    "imdb_rating": 8.0,
    "desc": "A young surgeon with autism and Savant syndrome is recruited into the pediatric surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives?",
    "network": "American Broadcasting Company",
    "videos_count": 124,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1203/thumb_z1K4mJwISETia59rrnMdXxzoSrZ.jpg",
    "url": "/en/shows/the-good-doctor",
    "watched_count": null
}, {
    "id": 1281,
    "title": "9-1-1",
    "translated_genres": "Drama",
    "created_at": "2018-01-04T03:37:01.788+03:00",
    "length": 43,
    "year": "2018",
    "imdb_rating": 7.9,
    "desc": "Explore the high-pressure experiences of police officers, paramedics and firefighters who are thrust into the most frightening, shocking and heart-stopping situations. These emergency responders must try to balance saving those who are at their most vulnerable with solving the problems in their own lives.",
    "network": "FOX",
    "videos_count": 103,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1281/thumb_nFfYZCyLhA4lS0Edg6hB3r2EOFW.jpg",
    "url": "/en/shows/9-1-1",
    "watched_count": null
}, {
    "id": 29,
    "title": "Desperate Housewives",
    "translated_genres": "Comedy, Drama, Romance",
    "created_at": "2012-08-13T21:26:59.164+04:00",
    "length": 43,
    "year": "2004",
    "imdb_rating": 7.6,
    "desc": "Secrets and truths unfold through the lives of female friends in one suburban neighborhood, after the mysterious suicide of a neighbor.",
    "network": "American Broadcasting Company",
    "videos_count": 180,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/29/thumb_i1zeXFOoHsEiNYsHii3ebS1Pnmz.jpg",
    "url": "/en/shows/desperate-housewives",
    "watched_count": null
}, {
    "id": 31,
    "title": "Modern family",
    "translated_genres": "Comedy",
    "created_at": "2012-08-19T15:17:42.544+04:00",
    "length": 22,
    "year": "2009",
    "imdb_rating": 8.5,
    "desc": "three different, but related, families and the trials they face in each of their own uniquely comedic ways.",
    "network": "American Broadcasting Company",
    "videos_count": 250,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/31/thumb_vmokjFmPtDZySnNTQd6uqYcTjNF.jpg",
    "url": "/en/shows/modern-family",
    "watched_count": null
}, {
    "id": 1326,
    "title": "Station 19",
    "translated_genres": "Drama",
    "created_at": "2018-03-02T23:32:58.488+03:00",
    "length": 42,
    "year": "2018",
    "imdb_rating": 7.0,
    "desc": "The series follows a group of heroic firefighters of the Seattle Fire Department at Station 19 from the captain down the ranks to the newest recruit in their personal and professional lives.",
    "network": "ABC",
    "videos_count": 102,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1326/thumb_Station_19.jpg",
    "url": "/en/shows/station-19",
    "watched_count": null
}, {
    "id": 76,
    "title": "The Office",
    "translated_genres": "Comedy, Romance",
    "created_at": "2012-10-13T17:13:52.788+04:00",
    "length": 24,
    "year": "2005",
    "imdb_rating": 9.0,
    "desc": "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium. Based on the hit BBC series.",
    "network": "NBC",
    "videos_count": 186,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/76/thumb_iP0uuzWOR5uornNpkkZiemVonMi.jpg",
    "url": "/en/shows/the-office",
    "watched_count": null
}, {
    "id": 1212,
    "title": "Star Trek: Discovery",
    "translated_genres": "Sci-Fi",
    "created_at": "2017-09-25T12:21:38.809+03:00",
    "length": 48,
    "year": "2017",
    "imdb_rating": 7.0,
    "desc": "Ten years before Kirk, Spock and the Enterprise, the USS Discovery discovers new worlds and lifeforms as one Starfleet officer learns to understand all things alien.",
    "network": "CBS All Access",
    "videos_count": 62,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1212/thumb_ihvG9dCEnVU3gmMUftTkRICNdJf.jpg",
    "url": "/en/shows/star-trek-discovery",
    "watched_count": null
}, {
    "id": 89,
    "title": "The Simpsons",
    "translated_genres": "Animation, Comedy, Family",
    "created_at": "2012-10-18T18:20:38.545+04:00",
    "length": 22,
    "year": "1989",
    "imdb_rating": 8.7,
    "desc": "The satiric adventures of a working class family in the misfit city of Springfield.",
    "network": "Fox Broadcasting Company",
    "videos_count": 766,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/89/thumb_yTZQkSsxUFJZJe67IenRM0AEklc.jpg",
    "url": "/en/shows/the-simpsons",
    "watched_count": null
}, {
    "id": 638,
    "title": "Chicago Med",
    "translated_genres": "Drama",
    "created_at": "2015-11-17T00:18:00.676+03:00",
    "length": 41,
    "year": "2015",
    "imdb_rating": 7.6,
    "desc": "An emotional thrill ride through the day-to-day chaos of the city's most explosive hospital and the courageous team of doctors who hold it together...",
    "network": "NBC",
    "videos_count": 174,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/638/thumb_Chicago_Med_s8.png",
    "url": "/en/shows/chicago-med",
    "watched_count": null
}, {
    "id": 360,
    "title": "Chicago P.D.",
    "translated_genres": "Action, Drama",
    "created_at": "2014-04-18T08:51:39.534+04:00",
    "length": 43,
    "year": "2014",
    "imdb_rating": 8.1,
    "desc": "Follows District 21 of the Chicago Police Department, which is made up of two distinctly different groups: the uniformed cops and the Intelligence Unit.",
    "network": "NBC",
    "videos_count": 218,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/360/thumb_Chicago_P.D._s10.png",
    "url": "/en/shows/chicago-pd",
    "watched_count": null
}, {
    "id": 48,
    "title": "How I Met Your Mother",
    "translated_genres": "Comedy, Romance",
    "created_at": "2012-09-20T22:21:24.940+04:00",
    "length": 22,
    "year": "2005",
    "imdb_rating": 8.3,
    "desc": "Ted searches for the woman of his dreams in New York City with the help of his four best friends.",
    "network": "CBS",
    "videos_count": 208,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/48/thumb_izncB6dCLV7LBQ5MsOPyMx9mUDa.jpg",
    "url": "/en/shows/how-i-met-your-mother",
    "watched_count": null
}, {
    "id": 373,
    "title": "Chicago Fire",
    "translated_genres": "Action, Drama",
    "created_at": "2014-05-01T16:59:26.988+04:00",
    "length": 42,
    "year": "2012",
    "imdb_rating": 8.0,
    "desc": "The story of firefighters in Chicago.",
    "network": "NBC",
    "videos_count": 248,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/373/thumb_Chicago_Fire_s11.png",
    "url": "/en/shows/chicago-fire",
    "watched_count": null
}, {
    "id": 77,
    "title": "Doctor Who",
    "translated_genres": "Adventure, Drama, Sci-Fi",
    "created_at": "2012-10-13T17:50:22.974+04:00",
    "length": 49,
    "year": "2005",
    "imdb_rating": 8.6,
    "desc": "The further adventures of the time traveling alien adventurer and his companions.",
    "network": "BBC One",
    "videos_count": 183,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/77/thumb_Doctor.jpg",
    "url": "/en/shows/doctor-who",
    "watched_count": null
}, {
    "id": 10,
    "title": "House M.D.",
    "translated_genres": "Drama, Mystery",
    "created_at": "2012-08-03T16:09:40.059+04:00",
    "length": 44,
    "year": "2004",
    "imdb_rating": 8.7,
    "desc": "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
    "network": "Fox Broadcasting Company",
    "videos_count": 178,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/10/thumb_lxSzRZ49NXwsiyHuvMsd19QxduC.jpg",
    "url": "/en/shows/house-m-d",
    "watched_count": null
}, {
    "id": 6,
    "title": "Game of Thrones",
    "translated_genres": "Adventure, Drama, Fantasy",
    "created_at": "2012-08-01T19:57:09.708+04:00",
    "length": 58,
    "year": "2011",
    "imdb_rating": 9.2,
    "desc": "Seven noble families fight for control of the mythical land of Westeros. ",
    "network": "HBO",
    "videos_count": 76,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/6/thumb_got-poster.jpg",
    "url": "/en/shows/game-of-thrones",
    "watched_count": null
}, {
    "id": 991,
    "title": "The Crown",
    "translated_genres": "Drama, History",
    "created_at": "2016-10-30T18:16:29.597+03:00",
    "length": 57,
    "year": "2016",
    "imdb_rating": 8.6,
    "desc": "The Crown focuses on Queen Elizabeth II as a 25-year-old newlywed faced with the daunting prospect of...",
    "network": "Netflix",
    "videos_count": 60,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/991/thumb_The_Crown_new_poster.jpg",
    "url": "/en/shows/the-crown",
    "watched_count": null
}, {
    "id": 2119,
    "title": "Ted Lasso",
    "translated_genres": "Comedy",
    "created_at": "2020-08-14T11:50:10.420+03:00",
    "length": 30,
    "year": "2020",
    "imdb_rating": 8.8,
    "desc": "Ted Lasso, an American football coach, moves to England when he’s hired to manage a soccer team—despite having no experience. With cynical players and a doubtful town, will he get them to see the Ted Lasso Way?",
    "network": "Apple TV+",
    "videos_count": 36,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/2119/thumb_oX7QdfiQEbyvIvpKgJHRCgbrLdK.jpg",
    "url": "/en/shows/ted-lasso",
    "watched_count": null
}, {
    "id": 182,
    "title": "Blue Bloods",
    "translated_genres": "Crime, Drama",
    "created_at": "2012-12-09T13:55:21.449+04:00",
    "length": 42,
    "year": "2010",
    "imdb_rating": 7.7,
    "desc": "Blue Bloods follows the lives of the NYPD's First Family of Law Enforcement: the Reagans. Frank, the Police Comissioner and son of former PC Henry Reagan, must balance his duties of running the largest police force in the world and being his kids' boss. His daughter Erin is an Assistant District Attorney, son Danny is a senior detective and fellow Marine Veteran, and new Harvard Law grad turned cop, Jamie all swirl through this family drama and passionately defend their city from harm. The Irish-American family is deeply rooted in their patriotism, passion, and love of family. ",
    "network": "CBS",
    "videos_count": 284,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/182/thumb_wpZ8w8HWVxLgCa8siz8bhrua6Qd.jpg",
    "url": "/en/shows/blue-bloods",
    "watched_count": null
}, {
    "id": 33,
    "title": "Breaking Bad",
    "translated_genres": "Crime, Drama, Thriller",
    "created_at": "2012-08-19T22:40:11.323+04:00",
    "length": 48,
    "year": "2008",
    "imdb_rating": 9.5,
    "desc": "Informed he has terminal cancer, an underachieving chemistry genius turned high school teacher uses his expertise to secretly provide for his family by producing the world's highest quality crystal meth.",
    "network": "AMC",
    "videos_count": 62,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/33/thumb_1yeVJox3rjo2jBKrrihIMj7uoS9.jpg",
    "url": "/en/shows/breaking-bad",
    "watched_count": null
}, {
    "id": 171,
    "title": "American Horror Story",
    "translated_genres": "Drama, Horror, Mystery, Sci-Fi, Thriller",
    "created_at": "2012-11-29T02:49:10.932+04:00",
    "length": 45,
    "year": "2011",
    "imdb_rating": 8.0,
    "desc": "An anthology series that centers on different characters and locations, including a haunted house and an insane asylum.",
    "network": "FX",
    "videos_count": 132,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/171/thumb_gH3JZCBvAmTyKSE5sJ8zzdHcn8S.jpg",
    "url": "/en/shows/american-horror-story",
    "watched_count": null
}, {
    "id": 137,
    "title": "Gilmore Girls",
    "translated_genres": "Comedy, Drama",
    "created_at": "2012-11-03T01:54:59.269+04:00",
    "length": 43,
    "year": "2000",
    "imdb_rating": 8.2,
    "desc": "A drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.",
    "network": "The WB Television Network",
    "videos_count": 153,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/137/thumb_mQs0u3PZoP13Qn9qzjPTECW5u1Y.jpg",
    "url": "/en/shows/gilmore-girls",
    "watched_count": null
}, {
    "id": 81,
    "title": "South Park",
    "translated_genres": "Animation, Comedy",
    "created_at": "2012-10-14T17:26:02.708+04:00",
    "length": 22,
    "year": "1997",
    "imdb_rating": 8.7,
    "desc": "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.",
    "network": "Comedy Central",
    "videos_count": 327,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/81/thumb_v9zc0cZpy5aPSfAy6Tgb6I1zWgV.jpg",
    "url": "/en/shows/south-park",
    "watched_count": null
}, {
    "id": 106,
    "title": "The Sopranos",
    "translated_genres": "Crime, Drama",
    "created_at": "2012-10-24T16:59:50.761+04:00",
    "length": 54,
    "year": "1999",
    "imdb_rating": 9.2,
    "desc": "Modern day morality tale about New Jersey mob boss Tony Soprano, as he deals with personal and professional issues in his home and business life.",
    "network": "HBO",
    "videos_count": 86,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/106/thumb_u0cLcBQITrYqfHsn06fxnQwtqiE.jpg",
    "url": "/en/shows/the-sopranos",
    "watched_count": null
}, {
    "id": 3154,
    "title": "Bluey",
    "translated_genres": "Animation, Family",
    "created_at": "2023-02-14T16:50:30.168+03:00",
    "length": 7,
    "year": "2018",
    "imdb_rating": 9.4,
    "desc": "Bluey is an inexhaustible six year-old Blue Heeler dog, who loves to play and turns everyday family life into extraordinary adventures, developing her imagination as well as her mental, physical and emotional resilience.",
    "network": "ABC KIDS",
    "videos_count": 154,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/3154/thumb_4FqOvBwQEFv3RHTjtmKp5LYLASR.jpg",
    "url": "/en/shows/bluey",
    "watched_count": null
}, {
    "id": 284,
    "title": "Brooklyn Nine-Nine",
    "translated_genres": "Comedy",
    "created_at": "2013-09-18T18:30:24.118+04:00",
    "length": 22,
    "year": "2013",
    "imdb_rating": 8.4,
    "desc": "A diverse group of detectives at the very edge of New York City.",
    "network": "Fox Broadcasting Company",
    "videos_count": 153,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/284/thumb_o40Wv2cCxbUUpBoDa7imlLE05mB.jpg",
    "url": "/en/shows/brooklyn-nine-nine",
    "watched_count": null
}, {
    "id": 92,
    "title": "Charmed(1998)",
    "translated_genres": "Comedy, Drama, Fantasy, Mystery",
    "created_at": "2012-10-19T21:44:12.596+04:00",
    "length": 43,
    "year": "1998",
    "imdb_rating": 7.1,
    "desc": "Three sisters discover their destiny - to battle against the forces of evil, using their witchcraft. They are the Charmed Ones.",
    "network": "The WB Television Network",
    "videos_count": 175,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/92/thumb_73xATBuGPysPWY6dKPko9YxjmPe.jpg",
    "url": "/en/shows/charmed-1998",
    "watched_count": null
}, {
    "id": 2933,
    "title": "Welcome to Wrexham",
    "translated_genres": "Documentary",
    "created_at": "2022-08-30T16:39:54.105+03:00",
    "length": null,
    "year": "2022",
    "imdb_rating": 8.3,
    "desc": "Documentary series tracking the dreams and worries of Wrexham, a working-class town in North Wales, UK, as two Hollywood stars (Rob McElhenney and Ryan Reynolds) take ownership of the town’s historic yet struggling football club.",
    "network": "FX",
    "videos_count": 36,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/2933/thumb_z5fZOpWI4FmJ3eSJsNkJjwEY4uZ.jpg",
    "url": "/en/shows/welcome-to-wrexham",
    "watched_count": null
}, {
    "id": 453,
    "title": "Rick and Morty",
    "translated_genres": "Animation, Adventure, Comedy, Sci-Fi",
    "created_at": "2014-09-10T10:47:57.898+04:00",
    "length": 22,
    "year": "2013",
    "imdb_rating": 9.1,
    "desc": "An animated series that follows the exploits of a super scientist and his not so bright grandson.",
    "network": "Adult Swim",
    "videos_count": 75,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/453/thumb_qJdfO3ahgAMf2rcmhoqngjBBZW1.jpg",
    "url": "/en/shows/rick-and-morty",
    "watched_count": null
}, {
    "id": 36,
    "title": "Suits",
    "translated_genres": "Comedy, Drama",
    "created_at": "2012-08-31T23:01:20.354+04:00",
    "length": 43,
    "year": "2011",
    "imdb_rating": 8.5,
    "desc": "On the run from a drug deal gone bad, Mike Ross, a brilliant college-dropout, finds himself a job working with Harvey Specter, one of New York City's best lawyers.",
    "network": "USA Network",
    "videos_count": 134,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/36/thumb_suits_season_eight.jpg",
    "url": "/en/shows/suit",
    "watched_count": null
}, {
    "id": 62,
    "title": "Supernatural",
    "translated_genres": "Drama, Fantasy, Horror, Mystery, Thriller",
    "created_at": "2012-10-04T09:50:37.638+04:00",
    "length": 42,
    "year": "2005",
    "imdb_rating": 8.4,
    "desc": "Two brothers follow their father's footsteps as \"hunters\" fighting evil supernatural beings of many kinds including monsters, demons, and gods that roam the earth.",
    "network": "The WB Television Network",
    "videos_count": 328,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/62/thumb_3iFm6Kz7iYoFaEcj4fLyZHAmTQA.jpg",
    "url": "/en/shows/supernatural",
    "watched_count": null
}, {
    "id": 39,
    "title": "The Vampire Diaries",
    "translated_genres": "Drama, Fantasy, Horror, Romance",
    "created_at": "2012-09-10T21:21:05.020+04:00",
    "length": 42,
    "year": "2009",
    "imdb_rating": 7.7,
    "desc": "A high school girl is torn between two vampire brothers.",
    "network": "The CW",
    "videos_count": 172,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/39/thumb_jZn7dEHRRjXcT43D9GMHxzASDef.jpg",
    "url": "/en/shows/the-vampire-diaries",
    "watched_count": null
}, {
    "id": 498,
    "title": "Better Call Saul",
    "translated_genres": "Comedy, Crime, Drama",
    "created_at": "2015-02-09T19:16:36.564+03:00",
    "length": 49,
    "year": "2015",
    "imdb_rating": 9.0,
    "desc": "The trials and tribulations of criminal lawyer, Saul Goodman, in the time leading up to establishing his strip-mall law office in Albuquerque, New Mexico.",
    "network": "AMC",
    "videos_count": 65,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/498/thumb_hxTOuZxPxl9mv9nfoCvesnJZg40.jpg",
    "url": "/en/shows/better-call-saul",
    "watched_count": null
}, {
    "id": 87,
    "title": "Castle",
    "translated_genres": "Comedy, Crime, Drama, Mystery",
    "created_at": "2012-10-17T12:57:20.446+04:00",
    "length": 42,
    "year": "2009",
    "imdb_rating": 8.1,
    "desc": "After a serial killer imitates the plots of his novels, successful mystery novelist Richard \"Rick\" Castle gets permission from the Mayor of New York City to tag along with an NYPD homicide investigation team for research purposes.",
    "network": "American Broadcasting Company",
    "videos_count": 173,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/87/thumb_hdtCGRP6yYQNqUSqCkCWidPMbgr.jpg",
    "url": "/en/shows/castle",
    "watched_count": null
}, {
    "id": 96,
    "title": "Shameless",
    "translated_genres": "Comedy, Drama",
    "created_at": "2012-10-20T20:12:00.549+04:00",
    "length": 54,
    "year": "2011",
    "imdb_rating": 8.6,
    "desc": "An alcoholic man lives in a perpetual stupor while his six children with whom he lives cope as best they can.",
    "network": "Showtime",
    "videos_count": 134,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/96/thumb_dSBYRw1R001azIUsaatQXZAOcXk.jpg",
    "url": "/en/shows/shameless",
    "watched_count": null
}, {
    "id": 358,
    "title": "Fargo",
    "translated_genres": "Crime, Drama",
    "created_at": "2014-04-16T15:55:19.812+04:00",
    "length": 52,
    "year": "2014",
    "imdb_rating": 8.9,
    "desc": "A drifter named Lorne Malvo arrives in small-town Minnesota and influences the population with his malice and violence, including put-upon insurance salesman Lester Nygaard.",
    "network": "FX",
    "videos_count": 51,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/358/thumb_sskPK2HjkFaxam10eg0Hk1A3I2m.jpg",
    "url": "/en/shows/fargo",
    "watched_count": null
}, {
    "id": 2177,
    "title": "Emily in Paris",
    "translated_genres": "Drama, Comedy",
    "created_at": "2020-10-01T22:14:51.339+03:00",
    "length": 23,
    "year": "2020",
    "imdb_rating": 6.9,
    "desc": "When ambitious Chicago marketing exec Emily unexpectedly lands her dream job in Paris, she embraces a new life as she juggles work, friends and romance.",
    "network": "Netflix",
    "videos_count": 30,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/2177/thumb_kwMqIYOC4U9eK4NZnmmyD8pDEOi.jpg",
    "url": "/en/shows/emily-in-paris",
    "watched_count": null
}, {
    "id": 63,
    "title": "Scrubs",
    "translated_genres": "Comedy, Drama",
    "created_at": "2012-10-04T16:42:36.731+04:00",
    "length": 22,
    "year": "2001",
    "imdb_rating": 8.4,
    "desc": "In the unreal world of Sacred Heart Hospital, intern John \"J.D\" Dorian learns the ways of medicine, friendship and life.",
    "network": "American Broadcasting Company",
    "videos_count": 180,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/63/thumb_x40NhjIPoDoTbT0z2utFgIedtwh.jpg",
    "url": "/en/shows/scrubs",
    "watched_count": null
}, {
    "id": 11,
    "title": "The Good Wife",
    "translated_genres": "Crime, Drama, Mystery",
    "created_at": "2012-08-03T16:09:58.579+04:00",
    "length": 43,
    "year": "2009",
    "imdb_rating": 8.4,
    "desc": "Alicia has been a good wife to her husband, a former state attorney. After a very humiliating sex and corruption scandal, he is behind bars. She must now provide for her family and returns to work as a litigator in a law firm.",
    "network": "CBS",
    "videos_count": 156,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/11/thumb_ljgxvwRXuKgdht3zREaasby1SzL.jpg",
    "url": "/en/shows/the-good-wife",
    "watched_count": null
}, {
    "id": 43,
    "title": "New Girl",
    "translated_genres": "Comedy",
    "created_at": "2012-09-17T15:44:24.792+04:00",
    "length": 22,
    "year": "2011",
    "imdb_rating": 7.8,
    "desc": "After a bad break-up, Jess, an offbeat young woman, moves into an apartment loft with three single men. Although they find her behavior very unusual, the men support her - most of the time.",
    "network": "Fox Broadcasting Company",
    "videos_count": 146,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/43/thumb_tvqi2y2FjiWTL5TRL1Pa6UX8Jef.jpg",
    "url": "/en/shows/new-girl",
    "watched_count": null
}, {
    "id": 104,
    "title": "The Mentalist",
    "translated_genres": "Crime, Drama, Mystery, Thriller",
    "created_at": "2012-10-22T17:30:29.275+04:00",
    "length": 43,
    "year": "2008",
    "imdb_rating": 8.1,
    "desc": "An infamous 'psychic' abandons his public persona, outing himself as a fake, to focus on his work as a consultant for the California Bureau of Investigation in order to find \"Red John,\" the madman who killed his wife and daughter.",
    "network": "CBS",
    "videos_count": 149,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/104/thumb_gdkkBruycNl9NlHFnxRuqVHfsvt.jpg",
    "url": "/en/shows/the-mentalist",
    "watched_count": null
}, {
    "id": 206,
    "title": "Criminal Minds",
    "translated_genres": "Crime, Drama, Mystery, Thriller",
    "created_at": "2013-01-16T00:52:12.038+04:00",
    "length": 42,
    "year": "2005",
    "imdb_rating": 8.1,
    "desc": "An elite group of profilers analyze the nation's most dangerous criminal minds in an effort to anticipate their next moves before they strike again.",
    "network": "CBS",
    "videos_count": 332,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/206/thumb_yULqQQFqrbWlTBUydqj93rQkcVe.jpg",
    "url": "/en/shows/criminal-minds",
    "watched_count": null
}, {
    "id": 1723,
    "title": "The Boys",
    "translated_genres": "Sci-Fi, Fantasy, Action, Adventure",
    "created_at": "2019-07-25T14:34:18.168+03:00",
    "length": 59,
    "year": "2019",
    "imdb_rating": 8.7,
    "desc": "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    "network": "Amazon",
    "videos_count": 24,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1723/thumb_dzOxNbbz1liFzHU1IPvdgUR647b.jpg",
    "url": "/en/shows/the-boys",
    "watched_count": null
}, {
    "id": 1357,
    "title": "Curb Your Enthusiasm",
    "translated_genres": "Comedy",
    "created_at": "2018-03-30T17:48:43.547+03:00",
    "length": 32,
    "year": "2000",
    "imdb_rating": 8.8,
    "desc": "The off-kilter, unscripted comic vision of Larry David, who plays himself in a parallel universe in which he can't seem to do anything right, and, by his standards, neither can anyone else.",
    "network": "HBO",
    "videos_count": 120,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1357/thumb_xBr9txlyX5ToPTS5n0tTcVvndhQ.jpg",
    "url": "/en/shows/curb-your-enthusiasm",
    "watched_count": null
}, {
    "id": 136,
    "title": "Parks and Recreation",
    "translated_genres": "Comedy",
    "created_at": "2012-11-02T20:45:13.643+04:00",
    "length": 22,
    "year": "2009",
    "imdb_rating": 8.6,
    "desc": "The absurd antics of an Indiana town's public officials as they pursue sundry projects to make their city a better place.",
    "network": "NBC",
    "videos_count": 122,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/136/thumb_nxevAIZdQGqbPBkk2EdIX0A20Gd.jpg",
    "url": "/en/shows/parks-and-recreation",
    "watched_count": null
}, {
    "id": 1289,
    "title": "Yellowstone",
    "translated_genres": "Drama",
    "created_at": "2018-01-15T19:55:13.422+03:00",
    "length": 50,
    "year": "2018",
    "imdb_rating": 8.7,
    "desc": "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
    "network": "Paramount Network",
    "videos_count": 47,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1289/thumb_lcmDSMFa6NVjeCg9IO9KCxErRj2.jpg",
    "url": "/en/shows/yellowstone",
    "watched_count": null
}, {
    "id": 300,
    "title": "Peaky Blinders",
    "translated_genres": "Drama",
    "created_at": "2013-10-08T11:18:39.021+04:00",
    "length": 58,
    "year": "2013",
    "imdb_rating": 8.8,
    "desc": "A British gangster saga set in 1920s Birmingham.",
    "network": "BBC Two",
    "videos_count": 37,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/300/thumb_AiqsuFFL2u4hsrMFYUbQlX9BqhH.jpg",
    "url": "/en/shows/peaky-blinders",
    "watched_count": null
}, {
    "id": 330,
    "title": "Peppa Pig",
    "translated_genres": "Animation, Family",
    "created_at": "2014-02-16T02:39:13.075+04:00",
    "length": 5,
    "year": "2004",
    "imdb_rating": 6.3,
    "desc": "Peppa is a loveable, cheeky little piggy who lives with her little brother George, Mummy Pig and Daddy Pig...",
    "network": "Channel 5",
    "videos_count": 257,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/330/thumb_WB9eS8cleiU8gQrxfkxicEVdmz.jpg",
    "url": "/en/shows/peppa-pig",
    "watched_count": null
}, {
    "id": 88,
    "title": "Futurama",
    "translated_genres": "Animation, Comedy, Sci-Fi",
    "created_at": "2012-10-17T16:02:39.581+04:00",
    "length": 21,
    "year": "1999",
    "imdb_rating": 8.5,
    "desc": "Fry, a pizza guy is accidentally frozen in 1999 and thawed out New Year's Eve 2999.",
    "network": "Fox Broadcasting Company",
    "videos_count": 138,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/88/thumb_Futurama-Hulu.png",
    "url": "/en/shows/futurama",
    "watched_count": null
}, {
    "id": 392,
    "title": "Call The Midwife",
    "translated_genres": "Drama",
    "created_at": "2014-05-21T19:44:15.396+04:00",
    "length": 60,
    "year": "2012",
    "imdb_rating": 8.6,
    "desc": "The lives of a group of midwives living in East London in the late 1950s.",
    "network": "BBC One",
    "videos_count": 114,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/392/thumb_p7kVnH6WtT6s6sexMSp2j8YN29d.jpg",
    "url": "/en/shows/call-the-midwife",
    "watched_count": null
}, {
    "id": 3452,
    "title": "Krapopolis",
    "translated_genres": "Animation, Comedy",
    "created_at": "2023-09-25T14:37:18.222+03:00",
    "length": 22,
    "year": "2023",
    "imdb_rating": 6.3,
    "desc": "In mythical ancient Greece, a flawed family of humans, gods and monsters tries to run one of the world’s first cities without killing each other.",
    "network": "FOX",
    "videos_count": 22,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/3452/thumb_6DlLqv0jlv64ojXh6erRhBa5S4l.jpg",
    "url": "/en/shows/krapopolis",
    "watched_count": null
}, {
    "id": 510,
    "title": "Avatar - The Last Airbender 2005",
    "translated_genres": "Animation, Action, Adventure, Family, Fantasy, Mystery",
    "created_at": "2015-04-05T14:38:43.687+03:00",
    "length": 24,
    "year": "2005",
    "imdb_rating": 9.3,
    "desc": "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar.",
    "network": "Nickelodeon",
    "videos_count": 54,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/510/thumb_sB8V0pQtJZ17v8FLXMOcYz6045c.jpg",
    "url": "/en/shows/avatar-the-last-airbender-2005",
    "watched_count": null
}, {
    "id": 108,
    "title": "Seinfeld",
    "translated_genres": "Comedy",
    "created_at": "2012-10-25T13:17:27.271+04:00",
    "length": 23,
    "year": "1989",
    "imdb_rating": 8.9,
    "desc": "The continuing misadventures of neurotic New York stand-up comedian Jerry Seinfeld and his equally neurotic New York friends.",
    "network": "NBC",
    "videos_count": 173,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/108/thumb_w7VV1jdtwzEC0c71AjUUA4T65Az.jpg",
    "url": "/en/shows/seinfeld",
    "watched_count": null
}, {
    "id": 1735,
    "title": "Why Women Kill",
    "translated_genres": "Comedy, Crime, Drama",
    "created_at": "2019-08-14T14:27:22.049+03:00",
    "length": 51,
    "year": "2019",
    "imdb_rating": 8.3,
    "desc": "Three women living in three different decades: a housewife in the '60s, a socialite in the '80s and a lawyer in 2018, deal with infidelity in their marriages.",
    "network": "CBS All Access",
    "videos_count": 20,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/1735/thumb_a6yrDXLGP54Mx7EfvQJFW8vfzbj.jpg",
    "url": "/en/shows/why-women-kill",
    "watched_count": null
}, {
    "id": 490,
    "title": "Gravity Falls",
    "translated_genres": "Animation, Comedy, Family, Fantasy, Mystery",
    "created_at": "2015-01-10T15:59:25.900+03:00",
    "length": 23,
    "year": "2012",
    "imdb_rating": 8.9,
    "desc": "Dipper and Mabel Pines spend the summer at their great uncle's tourist trap, The Mystery Shack. They think it's just going to be another usual summer, until mysterious things begin occurring all over town.",
    "network": "Disney XD",
    "videos_count": 41,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/490/thumb_oGsgxjeZ9rd20eCJsGSMGgWvl4P.jpg",
    "url": "/en/shows/gravity-falls",
    "watched_count": null
}, {
    "id": 2902,
    "title": "The Office EXTENDED",
    "translated_genres": "Comedy",
    "created_at": "2022-08-01T15:34:13.511+03:00",
    "length": 38,
    "year": "2005",
    "imdb_rating": 7.6,
    "desc": "The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
    "network": "NBC",
    "videos_count": 147,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/2902/thumb_qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    "url": "/en/shows/the-office-extended",
    "watched_count": null
}, {
    "id": 105,
    "title": "Two and a Half Men",
    "translated_genres": "Comedy",
    "created_at": "2012-10-24T13:35:30.820+04:00",
    "length": 21,
    "year": "2003",
    "imdb_rating": 7.1,
    "desc": "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
    "network": "CBS",
    "videos_count": 261,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/105/thumb_nli4nyzOIN9s5eOaGmPzHyVNnk0.jpg",
    "url": "/en/shows/two-and-a-half-men",
    "watched_count": null
}, {
    "id": 2457,
    "title": "The White Lotus",
    "translated_genres": "Comedy, Drama",
    "created_at": "2021-07-11T14:05:23.120+03:00",
    "length": 60,
    "year": "2021",
    "imdb_rating": 7.9,
    "desc": "Follow the exploits of various guests and employees at an exclusive tropical resort over the span of a week as with each passing day, a darker complexity emerges in these picture-perfect travelers, the hotel’s cheerful employees and the idyllic locale itself.",
    "network": "HBO",
    "videos_count": 13,
    "image": "https://uploads.ororo-mirror.tv/uploads/show/poster/2457/thumb_4gBYNDdczkFOqjR4dgYamqbp6cS.jpg",
    "url": "/en/shows/the-white-lotus",
    "watched_count": null
}]
export default shows